name: UI Snapshot Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ui-snapshot-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      - name: Run Storybook and UI Snapshot Tests
        id: run_tests
        run: |
          npm run storybook & 
          npx wait-on http://localhost:9009 && 
          npm run test:integration
        continue-on-error: true

      - name: Upload new snapshot artifacts
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: new-snapshot-artifacts
          path: integration/new_snapshots

      - name: Upload diff artifacts
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: diff-snapshot-artifacts
          path: integration/__image_snapshots__/__diff_output__

      - name: Upload screenshot artifacts
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: screenshot-artifacts
          path: integration/__image_snapshots__/

      - name: Set job status
        if: failure()
        run: exit 1
